version: 2

jobs:
  build:
    docker:
      - image: circleci/golang

    steps:
      - checkout
      - run: sleep 5

  chart:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4     

  "branch deploy":
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4 
  qa1:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4 

  qa2:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4 

  qa3:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4 
      
  qa4:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4 
  qa5:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4 
  qa6:
    docker:
      - image: circleci/golang
    steps:  
      - run: sleep 4                         

workflows:
  version: 2
  release:
    jobs:
    - build
    - chart
    - "branch deploy":
        requires:
          - chart

    - "qa2 approval":
        type: approval
        requires:
          - chart
    - "qa3 approval":
        type: approval
        requires:
          - chart
    - "qa4 approval":
        type: approval
        requires:
          - chart
    - "qa5 approval":
        type: approval
        requires:
          - chart
    - "qa6 approval":
        type: approval
        requires:
          - chart
    - qa1:
        requires:
          - chart
    - qa2:
        requires:
          - "qa2 approval"
    - qa3:
        requires:
          - "qa3 approval"
    - qa4:
        requires:
          - "qa4 approval"
    - qa5:
        requires:
          - "qa5 approval"
    - qa6:
        requires:
          - "qa6 approval" 
