version: 2.1

jobs:
  test:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run: docker build .

workflows:
  wf:
    jobs:
      - test:
          name: with/slash
