version: 2.1

executors:
  executor_machine:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  build-image:
    executor: executor_machine
    steps:
      - checkout
      - run:
          name: build image
          command: docker build .
      - run:
          name: check image
          command: |
             docker image ls
             ls -lh /home/node/TEST.txt

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-image
