version: 2.1

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build

jobs:
  build:

    docker:
      - image: cimg/python:3.8.5
    steps:
      - checkout
      - run:
          name: Run random commands
          command: |
              python --version
              uname -a
              uptime
