version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

jobs:
  build:
    docker:
      - image: circleci/golang

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          scp script.sh remote-docker:/tmp
          ssh -q remote-docker chmod +x /tmp/script.sh
          ssh -q -t remote-docker /tmp/script.sh
          ssh remote-docker docker version | grep Experimental
