version: 2.1

executors:
  executor_machine:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  build-image:
    executor: executor_machine
    steps:
      - checkout
      - run:
          name: build image
          command: docker build -t test123 .
      - run:
          name: check image and list TEST file
          command: |
             docker image ls
             docker run --name test_run -t -d test123
             docker exec test_run ls
             docker stop test_run

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 19.03.14
      - checkout
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
            sudo docker info
          EOF
      - run: |
          docker buildx build .

  build2:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          #version: 20.10.11
          version: 19.03.14
      - run:
          name: Create a new docker buildx builder instance
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install all
            docker context create multiarch-builder
            docker buildx create --use multiarch-builder

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build2
