version: 2.1

executors:
  executor_machine:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  build-image:
    executor: executor_machine
    steps:
      - checkout
      - run:
          name: build image
          command: docker build -t test123 .
      - run:
          name: check image
          command: |
             docker image ls
             docker run --name test_run --rm -it test123 /bin/sh
             docker exec test_run ls
             

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-image
