version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

jobs:
  build:
    - image: cimg/python:3.8.5
    #machine: 
      #mage: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: python --version
