version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

executors:
  default_exec: #declares a reusable executor to be used
    machine:
      docker_layer_caching: true
      
jobs:
  build:
    executor: default_exec
    #machine: 
      #mage: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Run Script
          command: |
             pwd
             ls -lh
             chmod +x sanity_test.sh
             set -x sanity_test.sh
