version: 2.1

workflows:
  build-deploy:
    jobs:
     - build

executors:
  default_exec: #declares a reusable executor to be used
    machine:

jobs:
  build:
    executor: default_exec
    steps:
      - checkout
      - run: | 
          pwd
          ls -lh
          chmod +x sanity_test.sh
          bash sanity_test.sh
