version: 2.1

workflows:

  wf-remote:
    jobs:
     - build

jobs:
  build:

    docker:
      - image: circleci/node

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13 
      - run:
          name: Build Docker image
          command: | 
             docker build -t test_image .
      - run: docker image ls
